### ISSUE TITLE
Build this package automatically

### ISSUE THREAD

**Issue by pgbezerra** [fulviocanducci/Canducci.MongoDB.Repository#1]
First of all, thank you for this repository! It really helps me.

I downloaded this package thought Nuget and I saw that Repository.Collection is protected, but in master branch it is public.
Then I realized that no CI was created to this repo.

If I create a PR to solve this, would you accept it?

To publish on NuGet we have to setup credentials in GitHub repo. So, to finish publisher, you should create an API key and set up on GitHub. 

Reference: https://github.com/marketplace/actions/publish-nuget

**Comment by fulviocanducci** [comment]
@paulobezerr 
Yes accepted
